import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage =>
  value === 'en' ? 'en' : value === 'ko' ? 'ko' : 'zh';

const REPORT_TEXT = {
  zh: {
    keyInsights: '核心洞察',
    noAnalysisSummary: '暂无分析结论',
    actionAdvice: '操作建议',
    noAdvice: '暂无建议',
    trendPrediction: '趋势预测',
    noPrediction: '暂无预测',
    marketSentiment: '市场情绪',
    strategyPoints: '策略点位',
    sniperLevels: '狙击点位',
    idealBuy: '理想买入',
    secondaryBuy: '二次买入',
    stopLoss: '止损价位',
    takeProfit: '止盈目标',
    noValue: '—',
    newsFeed: '资讯动态',
    relatedNews: '相关资讯',
    refresh: '刷新',
    retry: '重试',
    dismiss: '关闭',
    details: '查看详情',
    loadingNews: '加载资讯中...',
    noNews: '暂无相关资讯',
    noNewsDescription: '可稍后刷新以获取最新资讯。',
    openLink: '跳转',
    transparency: '透明度',
    traceability: '数据追溯',
    rawResult: '原始分析结果',
    analysisSnapshot: '分析快照',
    copy: '复制',
    copied: '已复制',
    recordId: '记录 ID',
    fullReport: '完整分析报告',
    loadingReport: '加载报告中...',
    loadReportFailed: '加载报告失败',
    copyMarkdownSource: '复制 Markdown 源码',
    copyPlainText: '复制纯文本',
    generateShareImage: '分享',
    generatingShareImage: '生成中...',
    shareImageReadyToShare: '再次点击分享',
    shareImageReady: '已生成',
    shareImageFailed: '重试',
    analysisModel: '分析模型',
    fearGreedIndex: '恐惧贪婪指数',
    boardLinkage: '板块联动',
    relatedBoards: '关联板块',
    leadingBoard: '领涨',
    laggingBoard: '领跌',
    neutralBoard: '中性',
    reanalyze: '重新分析',
    decisionContext: '决策上下文',
    decisionContextSubtitle: '从策略共识到最终结论的路径',
    strategyLayer: '策略层',
    finalDecisionLayer: '决策层',
    strategySynthesis: '多策略综合',
    strategyFinalSignal: '综合信号',
    strategyConsensus: '共识度',
    strategyConflict: '冲突',
    strategyConfidence: '置信度',
    supportingStrategies: '支持策略',
    opposingStrategies: '反方策略',
    riskDowngrade: '风控下调',
    riskDowngradeDetail: '风险信号触发后，最终信号已由 {from} 下调至 {to}。',
    layeringNote: '多策略综合为策略层共识；最终决策已综合风险（约占 30% 权重、高严重度信号封顶）与技术/资金面。',
    degradedWarning: '本次分析存在数据降级或阶段异常，结论稳健性下降。',
    noDecisionContext: '无策略综合与风控信息',
    unknown: '未知',
  },
  en: {
    keyInsights: 'KEY INSIGHTS',
    noAnalysisSummary: 'No analysis summary yet',
    actionAdvice: 'Action Advice',
    noAdvice: 'No advice yet',
    trendPrediction: 'Trend Outlook',
    noPrediction: 'No forecast yet',
    marketSentiment: 'Market Sentiment',
    strategyPoints: 'STRATEGY POINTS',
    sniperLevels: 'Action Levels',
    idealBuy: 'Ideal Entry',
    secondaryBuy: 'Secondary Entry',
    stopLoss: 'Stop Loss',
    takeProfit: 'Take Profit',
    noValue: '—',
    newsFeed: 'NEWS FEED',
    relatedNews: 'Related News',
    refresh: 'Refresh',
    retry: 'Retry',
    dismiss: 'Close',
    details: 'View details',
    loadingNews: 'Loading news...',
    noNews: 'No related news',
    noNewsDescription: 'Refresh later to check for the latest updates.',
    openLink: 'Open',
    transparency: 'TRANSPARENCY',
    traceability: 'Data Traceability',
    rawResult: 'Raw Analysis Result',
    analysisSnapshot: 'Analysis Snapshot',
    copy: 'Copy',
    copied: 'Copied!',
    recordId: 'Record ID',
    fullReport: 'Full Analysis Report',
    loadingReport: 'Loading report...',
    loadReportFailed: 'Failed to load report',
    copyMarkdownSource: 'Copy Markdown Source',
    copyPlainText: 'Copy Plain Text',
    generateShareImage: 'Share',
    generatingShareImage: 'Preparing...',
    shareImageReadyToShare: 'Share now',
    shareImageReady: 'Ready',
    shareImageFailed: 'Retry',
    analysisModel: 'Model',
    fearGreedIndex: 'Fear & Greed Index',
    boardLinkage: 'BOARD LINKAGE',
    relatedBoards: 'Related Boards',
    leadingBoard: 'Leading',
    laggingBoard: 'Lagging',
    neutralBoard: 'Neutral',
    reanalyze: 'Reanalyze',
    decisionContext: 'Decision Context',
    decisionContextSubtitle: 'Path from strategy consensus to the final conclusion',
    strategyLayer: 'Strategy layer',
    finalDecisionLayer: 'Decision layer',
    strategySynthesis: 'Strategy Synthesis',
    strategyFinalSignal: 'Final Signal',
    strategyConsensus: 'Consensus',
    strategyConflict: 'Conflict',
    strategyConfidence: 'Confidence',
    supportingStrategies: 'Supporting',
    opposingStrategies: 'Opposing',
    riskDowngrade: 'Risk Downgrade',
    riskDowngradeDetail: 'A risk signal downgraded the final signal from {from} to {to}.',
    layeringNote: 'The strategy synthesis is a strategy-layer consensus; the final decision also factors in risk (≈30% weight, high-severity signals cap at hold) and technical/capital flow.',
    degradedWarning: 'Some data was degraded or a stage anomaly occurred, reducing confidence in the conclusion.',
    noDecisionContext: 'No strategy synthesis or risk information',
    unknown: 'Unknown',
  },
  ko: {
    keyInsights: '핵심 인사이트',
    noAnalysisSummary: '분석 결론 없음',
    actionAdvice: '대응 전략',
    noAdvice: '제안 없음',
    trendPrediction: '추세 전망',
    noPrediction: '예측 없음',
    marketSentiment: '시장 심리',
    strategyPoints: '전략 가격대',
    sniperLevels: '대응 가격대',
    idealBuy: '이상적 매수가',
    secondaryBuy: '추가 매수가',
    stopLoss: '손절가',
    takeProfit: '목표가',
    noValue: '—',
    newsFeed: '뉴스 피드',
    relatedNews: '관련 뉴스',
    refresh: '새로고침',
    retry: '다시 시도',
    dismiss: '닫기',
    details: '상세 보기',
    loadingNews: '뉴스 불러오는 중...',
    noNews: '관련 뉴스 없음',
    noNewsDescription: '잠시 후 새로고침하여 최신 소식을 확인하세요.',
    openLink: '열기',
    transparency: '투명성',
    traceability: '데이터 추적',
    rawResult: '원본 분석 결과',
    analysisSnapshot: '분석 스냅샷',
    copy: '복사',
    copied: '복사됨!',
    recordId: '레코드 ID',
    fullReport: '전체 분석 리포트',
    loadingReport: '리포트 불러오는 중...',
    loadReportFailed: '리포트 불러오기 실패',
    copyMarkdownSource: 'Markdown 소스 복사',
    copyPlainText: '일반 텍스트 복사',
    generateShareImage: '공유',
    generatingShareImage: '생성 중...',
    shareImageReadyToShare: '지금 공유',
    shareImageReady: '완료',
    shareImageFailed: '다시 시도',
    analysisModel: '분석 모델',
    fearGreedIndex: '공포·탐욕 지수',
    boardLinkage: '섹터 연동',
    relatedBoards: '관련 섹터',
    leadingBoard: '강세',
    laggingBoard: '약세',
    neutralBoard: '중립',
    reanalyze: '재분석',
    decisionContext: '의사결정 컨텍스트',
    decisionContextSubtitle: '전략 컨센서스부터 최종 결론까지의 경로',
    strategyLayer: '전략 레이어',
    finalDecisionLayer: '결정 레이어',
    strategySynthesis: '전략 종합',
    strategyFinalSignal: '종합 신호',
    strategyConsensus: '공감도',
    strategyConflict: '충돌',
    strategyConfidence: '신뢰도',
    supportingStrategies: '지지 전략',
    opposingStrategies: '반대 전략',
    riskDowngrade: '리스크 하향',
    riskDowngradeDetail: '리스크 신호로 인해 최종 신호가 {from}에서 {to}로 하향 조정되었습니다.',
    layeringNote: '전략 종합은 전략 레이어의 합의이며, 최종 결정에는 리스크(약 30% 가중치, 고심각도 신호는 hold로 캡)와 기술/자금 흐름도 반영됩니다.',
    degradedWarning: '일부 데이터가 저하되거나 단계 이상이 발생해 결론 신뢰도가 낮아졌습니다.',
    noDecisionContext: '전략 종합 또는 리스크 정보 없음',
    unknown: '알 수 없음',
  },
} as const;

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
